apiVersion: v1
kind: Secret
metadata:
  name: secret-credentials
  namespace: {{ template "jenkins.namespace" . }}
data:
{{- range $key, $val := (lookup "v1" "Secret" "default" "files").data }}
  {{ $key | replace "_" "-" | replace ".cert" "" }}: {{ $val }}

{{- end }}

{{- range $key, $val := (lookup "v1" "Secret" "default" "secret-credentials").data }}
  {{ $key }}: {{ $val  }}
{{- end }}
